version: '3.7'

services:
    db:
        image: postgres:12
        container_name: postgres
        restart: always
        volumes:
            - /home/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env.prod.db

    api:
        container_name: api
        volumes:
            - static:/home/api/app/staticfiles
            - media:/home/api/app/mediafiles
        env_file:
            - /home/env
        build:
            context: ./api/
            dockerfile: Dockerfile.prod
        command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./nginx 
        volumes:
            - static:/home/api/app/staticfiles
            - media:/home/api/app/mediafiles
            - /home/nginx:/etc/nginx/conf.d
            - /home/certbot/conf:/etc/letsencrypt
            - /home/certbot/www:/var/www/certbot 
        ports:
            - 80:80
            - 443:443
        command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - api
    certbot:
        container_name: certbot
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /home/certbot/conf:/etc/letsencrypt
            - /home/certbot/www:/var/www/certbot

volumes:
    static:
    media:
