version: '3.7'

services:
    db:
        image: postgres:12
        container_name: postgres
          # restart: always
        volumes:
            - /home/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - /home/.env

    api:
        container_name: api
        volumes:
            - static:/home/api/staticfiles
            - media:/home/api/mediafiles
        command: sh -c "gunicorn api.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - /home/env
        build: /home/api/
        expose:
            - 8000  
        depends_on:
            - db

    nginx:
        container_name: nginx
        build: ./nginx 
        volumes:
            - static:/home/api/staticfiles
            - media:/home/api/mediafiles
            - /home/nginx:/etc/nginx/conf.d
            - /home/certbot/conf:/etc/letsencrypt
            - /home/certbot/www:/var/www/certbot 
        ports:
            - 80:80
            - 443:443
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        depends_on:
            - api
    certbot:
        container_name: certbot
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - /home/certbot/conf:/etc/letsencrypt
            - /home/certbot/www:/var/www/certbot

volumes:
    static:
    media:
